name: Build nginx base
on:
  push:
    paths:
      - '.ci/docker/nginx/**'
    branches:
      - 'feature/**'
      - 'improvement/**'
      - 'hotfix/**'
jobs:
  nginx:
    name: Publish nginx base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run hadolint on Dockerfile
        run: "docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 --ignore DL3007 - < .ci/docker/nginx/base/Dockerfile"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./.ci/docker/nginx/base/Dockerfile
          push: true
          tags: ghcr.io/pierreribault/laravel-test-nginx:base
