name: Build php-fpm base
on:
  push:
    paths:
      - 'ci/docker/php-fpm/**'
    branches:
      - 'feature/**'
      - 'improvement/**'
      - 'hotfix/**'
jobs:
  ofelia:
    name: Publish php-fpm base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run hadolint on Dockerfile
        run: "docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 --ignore DL3007 - < ci/docker/php-fpm/base/Dockerfile"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .ci/docker/php-fpm/base/Dockerfile
          push: true
          tags: laravel-test-php-fpm:base
