name: CI Workflow
on:
  push:
    branches:
      - 'develop'

jobs:
  php-fpm:
    runs-on: ubuntu-latest
    name: Preprare and push php-fpm staging
    steps:
      - uses: actions/checkout@master

      - name: Run hadolint on Dockerfile
        run: "docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 --ignore DL3007 - < .docker/php-fpm/Dockerfile"

      - name: Get Composer Cache Directory
        id: composer-cache
        working-directory: ./application
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Add nova repository
        working-directory: ./application
        run: |
          composer config http-basic.nova.laravel.com "${{ secrets.LARAVEL_NOVA_USER}}" "${{ secrets.LARAVEL_NOVA_PASSWORD}}"

      - name: Composer install
        working-directory: ./application
        run: |
          composer install --ignore-platform-reqs --no-progress

            - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Npm install
        working-directory: ./application
        run: |
          npm install

      - name: Npm install
        working-directory: ./application
        run: |
          npm run production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: .docker/php-fpm/Dockerfile
          push: true
          cache-from: ghcr.io/pierreribault/laravel-test-php-fpm:base
          tags: ghcr.io/pierreribault/laravel-test-php-fpm:staging